sudo: required
dist: trusty
language: cpp
compiler: g++
script: ./Client/configure && make -C ./Client/build && ./Server/configure && make -C ./Server/build
install: export CXX="g++-5"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5