sudo: required
dist: trusty
language: cpp
compiler: g++
script: cd Client && ./configure && make -C build && cd ../Server && ./configure && make -C build && make -C build/test && ./test/tests
install:
  - export CXX="g++-5"
  - sudo apt-get install libgtest-dev
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
